apiVersion: apps/v1
kind: Deployment
metadata:
  name: logs-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logs
  template:
    metadata:
      labels:
        app: logs
    spec:
      volumes:
        - name: shared-logs
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: log-provider
          image: fialco/log-provider:1.1
          env:
            - name: PORT
              value: "3000"
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/files
        - name: log-generator
          image: fialco/log-generator:1.1
          env:
            - name: PORT
              value: "3000"
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/files
