apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: ping-pong-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-app
  template:
    metadata:
      labels:
        app: ping-pong-app
    spec:
      #volumes:
      #  - name: shared-logs
      #    persistentVolumeClaim:
      #      claimName: image-claim
      containers:
        - name: ping-pong
          image: fialco/ping-pong:1.2
          env:
            - name: PORT
              value: "3000"
          #volumeMounts:
          #  - name: shared-logs
          #    mountPath: /usr/src/app/files
