apiVersion: v1
kind: Service
metadata:
  namespace: project
  name: todo-app-svc
spec:
  type: ClusterIP
  selector:
    app: todo-app # This is the app as declared in the deployment.
  ports:
    - port: 5173
      protocol: TCP
      targetPort: 5173 # This is the target port
